name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: hub.oepkgs.net
        username: ${{ vars.DOCKERHUB_OEPKGS_OERVCI_USERNAME }}
        password: ${{ secrets.DOCKERHUB_OEPKGS_OERVCI_TOKEN }}
